export {default as HomePage} from './homePage/HomePage'
export {default as Attractions} from './attractions/Attractions'
export {default as Restaurants} from './restaurants/Restaurants'
export {default as Architecture} from './architecture/Architecture'
export {default as NothingHere} from './nothingHere/NothingHere'
